name = "goes_wallpaper"
description = "Fetch an image from the GOES satellites and set it as a wallpaper"
version = "0.1.0-dev"

authors = ["Jacob Killelea"]
maintainers = ["Jacob Killelea <jacobkillelea@gmail.com>"]
maintainers-logins = ["Jkillelea"]
licenses = "GPL-3.0-or-later"
website = ""
tags = []

executables = ["goes_wallpaper"]

[[depends-on]]
aws = "^23.0.0"
